version: "3.6"
services:
  taxi-db:
    image: mdillon/postgis:9.4
    restart: always
    container_name: taxi-db
    environment:
      POSTGRES_DB: taxis_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - ./dbData:/var/lib/postgresql/data